name: test

on:
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.12
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: install requirements
              env:
                NOTION_DB_TOK: ${{ secrets.NOTION_DB_TOK }}
              run: |
                git clone git@github.com:hczhai/auto-gh-actions.git
                cd auto-gh-actions
                python3 test.py
